apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - redis.yaml
  - consul-statefulset.yaml
  - consul-importer.yaml
  - zipkin.yaml
  - keycloak.yaml
  - multiplication.yaml
  - gamification.yaml
  - logs.yaml
  - gateway.yaml
  - challenges-frontend.yaml
  - ingress.yaml
